#!/usr/bin/env python3
"""pearde capabilities — the registry of every verb `pearde` dispatches: what
exists, never what to run.

    capabilities.py [check]     no `check`: regenerate capabilities.md and
                                print it. `check`: one problem per line,
                                silent when clean

@index.md maps *files*, a skill's frontmatter maps *entry points*, and
`pearde.py` `discover()` maps `COMMANDS` at runtime — three answers to three
different questions, none of them "what can I do right now, with what, at
what cost". This is the union, generated from the same walk `pearde.py`
already does: one row per verb — name, one-line contract (its docstring's
first line), reads, writes, cost class.

Never hand-written. `capabilities.md`, at the repo root beside `index.md`, is
rewritten in full on every `pearde capabilities` — there is no partial edit
to make by hand, and `check` reports the file stale (or drifted: a row
naming a dead verb, a verb with no row) rather than trusting its mtime,
because a hand-edit does not always touch the mtime a `git checkout` also
moves.

reads / writes / cost class: a verb declares them by setting `.reads`,
`.writes` and `.cost` on the function `COMMANDS` exposes — the same
attribute the `.flags` a `--help` line reads uses. Cost class is one of
`shell`, `python`, `network`, `human`; a script `pearde.py` forwards to
that never declares `.cost` gets the class its own extension implies — the
`.sh` scripts are `shell`, the `.py` scripts are `python`. Undeclared reads
and writes print `—`: nothing in this tree names them yet, and a placeholder
is the honest answer until the commands that touch files and network start
declaring it, the way `.flags` was adopted one command at a time.

Python 3 stdlib only.
"""
import os
import sys

_D = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _D if os.path.isfile(os.path.join(_D, "pearde_path.py"))
                else os.path.dirname(_D))
import pearde_path  # noqa: E402,F401 — @resources/pearde_path.py, the one rule
import pearde as _pearde  # noqa: E402 — discover(), FORWARD, docstring(), title_line()

ROOT = pearde_path.skill_root(__file__)
REGISTRY = os.path.join(ROOT, "capabilities.md")

HEADER = ("<!-- Generated by `pearde capabilities`. Do not edit — "
          "`pearde capabilities check` fails on a drifted or hand-edited "
          "file. -->")


def _contract(name):
    """One line: what the verb does, from the same docstring `help` reads."""
    if name in _pearde.FORWARD:
        script = _pearde.FORWARD[name][0]
        title = _pearde.title_line(script)
        if title:
            return title
        doc = _pearde.docstring(script).strip().splitlines()
        return doc[0] if doc else ""
    fn = _pearde.discover()[0][name][1]
    doc = (fn.__doc__ or "").strip().splitlines()
    return doc[0] if doc else ""


def _cost(name):
    if name in _pearde.FORWARD:
        # a forwarded command has no single function `pearde.py` holds to
        # read a `.cost` attribute off — the extension it forwards to is
        # the cost class every script in this tree has today.
        script = _pearde.FORWARD[name][0]
        return "shell" if script.endswith(".sh") else "python"
    fn = _pearde.discover()[0][name][1]
    return getattr(fn, "cost", "python")


def _reads_writes(name):
    if name in _pearde.FORWARD:
        return "—", "—"
    fn = _pearde.discover()[0][name][1]
    return getattr(fn, "reads", "—"), getattr(fn, "writes", "—")


def verbs():
    """[(name, contract, reads, writes, cost)], every verb `pearde.py`
    dispatches — `FORWARD`'s names and `discover()`'s, sorted. The same
    union `pearde help` prints, at the same grain: one row per top-level
    name, not one per sub-verb — `memo list` and `memo check` are the verb
    `memo`."""
    found, problems = _pearde.discover()
    names = sorted(set(_pearde.FORWARD) | set(found))
    out = []
    for name in names:
        contract = _contract(name)
        reads, writes = _reads_writes(name)
        cost = _cost(name)
        out.append((name, contract, reads, writes, cost))
    return out, problems


def render(rows):
    lines = ["# Capabilities", "", HEADER, "",
             "One row per verb `pearde` dispatches — what exists, never "
             "what to run.", "",
             "| verb | contract | reads | writes | cost |",
             "|---|---|---|---|---|"]
    for name, contract, reads, writes, cost in rows:
        contract = (contract or "—").replace("|", "\\|")
        lines.append(f"| `{name}` | {contract} | {reads} | {writes} | {cost} |")
    return "\n".join(lines) + "\n"


def write():
    rows, problems = verbs()
    text = render(rows)
    with open(REGISTRY, "w", encoding="utf-8") as f:
        f.write(text)
    return text, problems


def check():
    """Drift, the way `index.py check` convicts the file manifest: a row
    naming a verb `pearde.py` no longer discovers, a discovered verb with no
    row, or a file that a hand-edit moved away from what regeneration would
    write — reported as `stale`, since the fix is the same for all three:
    run `pearde capabilities`."""
    problems = []
    rows, live_problems = verbs()
    live = {r[0] for r in rows}
    have_text = (open(REGISTRY, encoding="utf-8").read()
                 if os.path.isfile(REGISTRY) else None)
    if have_text is None:
        problems.append("capabilities.md is missing — run `pearde capabilities`")
        return problems + live_problems
    have_names = set()
    for line in have_text.splitlines():
        if line.startswith("| `"):
            have_names.add(line.split("`")[1])
    for name in sorted(have_names - live):
        problems.append(f"capabilities.md names `{name}` — no such verb")
    for name in sorted(live - have_names):
        problems.append(f"`{name}` is a verb with no row in capabilities.md")
    if have_text != render(rows) and not problems:
        problems.append("capabilities.md is stale — run `pearde capabilities`")
    return problems + live_problems


def main(argv):
    cmd = argv[1] if len(argv) > 1 else None
    if cmd == "check":
        problems = check()
        if problems:
            print("\n".join(problems))
        return 1 if problems else 0
    text, problems = write()
    sys.stdout.write(text)
    for p in problems:
        print(f"pearde capabilities: {p}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
