#!/usr/bin/env bash
# verify.sh — a fresh `init --example` board is one doctor calls green.
#
# Three obligations, driven rather than read:
#
#   1. the memo kind-index is regenerated after the copy — `--example` copies
#      through `ignore_patterns("README.md")`, which drops `memos/README.md`
#      as well as the example's own page, so the board lands with a memo and
#      no index and `memo check` calls it stale;
#   2. the knowledge graph is planted the way `upgrade` does it — `init`
#      planted the layer's files and never ran `knowledge.py board`/`relink`,
#      so `graph.json` was missing on a board one command old;
#   3. doctor answers under a home that holds no Obsidian config — the
#      quickstart's reader has not installed Obsidian, and a missing register
#      is a fact about the machine, not a fault in the board.
#
# Everything runs on a copy of the repo built from `git ls-files`, so the
# index row reads the tree as a clone holds it and no untracked drop of a
# neighbour's decides this probe. Every fixture is under one `mktemp -d`
# removed at exit. The daemon runs on a port the kernel gave us (bind 0), and
# its registry lives beside the copy, so the live daemon is never touched —
# asserted at the end.
#
# The last check is the neighbour harness this unit's red actually surfaced
# in. Under the board's own sweep it stands down, because the sweep runs that
# harness itself — and a stood-down check reports `skip`, which is never
# counted as a pass.
set -u
ROOT="$(cd "$(dirname "$0")/../../../../.." && pwd)"
NEIGHBOUR="$ROOT/.pearde/prds/the-board-runs-itself/readme-in-three-rings/probe"
TOP="$(mktemp -d)"
COPY="$TOP/pearde"; SKILLS="$TOP/skills"
REG="$ROOT/resources/board/state/serve.json"
REG_BEFORE="$( [ -f "$REG" ] && cksum < "$REG" )"
SPARE="$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()')"
export PEARDE_PORT="$SPARE" PEARDE_AS=engineer
cleanup() {
  PEARDE_PORT="$SPARE" python3 "$COPY/resources/board/serve.py" stop >/dev/null 2>&1
  rm -rf "$TOP"
}
trap cleanup EXIT

PASS=0; FAIL=0; SKIP=0
ok()   { PASS=$((PASS+1)); echo "  ok    $1"; }
bad()  { FAIL=$((FAIL+1)); echo "  FAIL  $1"; }
skip() { SKIP=$((SKIP+1)); echo "  skip  $1"; }
eq()   { [ "$2" = "$3" ] && ok "$1" || bad "$1 — got: $2 · want: $3"; }
has()  { printf '%s' "$2" | grep -qF -- "$3" && ok "$1" \
         || bad "$1 — missing: $3"; }
lacks(){ printf '%s' "$2" | grep -qF -- "$3" && bad "$1 — present: $3" \
         || ok "$1"; }

mkdir -p "$COPY" "$SKILLS"
( cd "$ROOT" && git ls-files -z | rsync -a0 --files-from=- "$ROOT/" "$COPY/" )
DOC="$COPY/resources/doctor.sh"
INIT="$COPY/resources/board/init.py"
GREEN="pearde: every part this repo owns checks out."
# a row's verdict, name and ok|broken|off only — the text after it is where
# the vault row is *meant* to differ between two homes
rows() { printf '%s\n' "$1" | sed -nE 's/^  ([a-z]+) +(ok|broken|off) .*/\1 \2/p'; }
vault() { printf '%s\n' "$1" | grep -E '^  vault '; }
# the verdict FIELD, never a substring of the row: `ok` is inside `broken`,
# so `grep -F ok` over a row is a check that cannot fail. Prints the bare
# word, or nothing when the row is absent.
verdict() { printf '%s\n' "$2" | sed -nE "s/^  $1 +(ok|broken|off) .*/\\1/p"; }

echo "A. init --example lands a board, and says what it seeded"
PROJ="$TOP/proj"; mkdir -p "$PROJ"; ( cd "$PROJ" && git init -q . )
OUT="$(cd "$PROJ" && python3 "$INIT" init --example 2>&1)"; RC=$?
eq  "A init --example exits 0" "$RC" "0"
has "A ...and names the index it regenerated" "$OUT" \
    "init: regenerated memos/README.md, the memo index by kind"
has "A ...and the board verb of the knowledge layer" "$OUT" \
    "init: knowledge board — board:"
has "A ...and the relink that writes the graph" "$OUT" \
    "init: knowledge relink — relink:"

echo "B. the memo kind-index exists and is not stale"
eq  "B memos/README.md is on the board" \
    "$( [ -f "$PROJ/.pearde/memos/README.md" ] && echo yes || echo no )" "yes"
MC="$(python3 "$COPY/resources/memos.py" check "$PROJ" 2>&1)"; MRC=$?
eq  "B memo check exits 0" "$MRC" "0"
eq  "B ...and says nothing" "$(printf '%s' "$MC" | wc -c | tr -d ' ')" "0"
has "B the index is the generated page, not a copied one" \
    "$(cat "$PROJ/.pearde/memos/README.md")" \
    "<!-- Generated by \`memo index\` and rewritten by \`memo add\`;"
eq  "B ...and byte-identical to the example board's own page" \
    "$(cmp -s "$PROJ/.pearde/memos/README.md" \
              "$COPY/resources/board/example/memos/README.md" \
       && echo same || echo differs)" "same"

# A `memos.py index` that fails must be *said*, not swallowed. A board that
# holds memos and no index is one doctor calls broken on the next line, so an
# `init` that exits 0 in silence has claimed a board it did not finish. The
# mutation lands on the COPY's memos.py only — the repo is never written —
# and the restore is proven with `cmp` before the section ends.
cp "$COPY/resources/memos.py" "$TOP/memos.py.bak"
python3 - "$COPY/resources/memos.py" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read()
s = s.replace(
    '    if cmd == "index":\n        print(write_index(board))\n        return 0\n',
    '    if cmd == "index":\n'
    '        print("memos: cannot write the index", file=sys.stderr)\n'
    '        return 1\n')
open(p, "w").write(s)
PY
eq  "B the failing-index mutation reached the copy" \
    "$(grep -c 'cannot write the index' "$COPY/resources/memos.py")" "1"
RO="$TOP/ro"; mkdir -p "$RO"; ( cd "$RO" && git init -q . )
ROUT="$(cd "$RO" && python3 "$INIT" init --example 2>&1)"
has "B a failing memo index is said, not swallowed" "$ROUT" \
    "init: could not regenerate memos/README.md"
has "B ...naming what memos.py reported" "$ROUT" "cannot write the index"
cp "$TOP/memos.py.bak" "$COPY/resources/memos.py"
eq  "B ...and the copy is restored" \
    "$(cmp -s "$TOP/memos.py.bak" "$COPY/resources/memos.py" \
       && echo same || echo differs)" "same"

echo "C. the knowledge graph is planted the way upgrade plants it"
eq  "C wiki/.graphify/graph.json exists" \
    "$( [ -f "$PROJ/.pearde/wiki/.graphify/graph.json" ] && echo yes || echo no )" "yes"
KD="$(python3 "$COPY/resources/knowledge.py" --root "$PROJ/.pearde/wiki" doctor 2>&1)"; KRC=$?
eq  "C knowledge doctor exits 0" "$KRC" "0"
has "C ...and calls the graph in sync" "$KD" "graph in sync"

echo "D. doctor calls the fresh board green"
D1="$(bash "$DOC" "$PROJ" 2>&1)"; DRC=$?
eq  "D doctor exits 0" "$DRC" "0"
has "D ...and closes green" "$D1" "$GREEN"
eq  "D the memos row reads ok" "$(verdict memos "$D1")" "ok"
eq  "D the knowledge row reads ok" "$(verdict knowledge "$D1")" "ok"
has "D init ran that same doctor and it closed green there too" "$OUT" "$GREEN"

echo "E. doctor under a home that holds no Obsidian config"
NOOBS="$TOP/no-obsidian"; mkdir -p "$NOOBS"
D2="$(env -u XDG_CONFIG_HOME HOME="$NOOBS" bash "$DOC" "$PROJ" 2>&1)"; D2RC=$?
eq  "E doctor exits 0 there" "$D2RC" "0"
has "E ...and closes green" "$D2" "$GREEN"
eq  "E the vault row answers rather than faulting" "$(verdict vault "$D2")" "ok"
has "E ...naming the machine, not the board" "$(vault "$D2")" \
    "Obsidian not installed here"
# tripwire: an extractor that reads nothing makes the diff below a check
# that cannot fail — this pins that it read the whole report first
RN=$(rows "$D1" | wc -l | tr -d ' ')
eq  "E the row reader read the whole report — 18 rows, not zero" "$RN" "18"
eq  "E no row's verdict moves between the two homes" \
    "$(diff <(rows "$D1") <(rows "$D2") | grep -c '^[<>] ' || true)" "0"
lacks "E doctor did not trip over an unset name" "$D2" "unbound variable"

echo "F. an empty board is still empty — no page written over nothing"
BARE="$TOP/bare"; mkdir -p "$BARE"; ( cd "$BARE" && git init -q . )
BOUT="$(cd "$BARE" && python3 "$INIT" init 2>&1)"; BRC=$?
eq  "F init exits 0" "$BRC" "0"
eq  "F memos/ holds no generated index — there is nothing to index" \
    "$( [ -e "$BARE/.pearde/memos/README.md" ] && echo yes || echo no )" "no"
lacks "F ...and init claims none" "$BOUT" "regenerated memos/README.md"
has "F doctor calls the empty board green too" \
    "$(bash "$DOC" "$BARE" 2>&1)" "$GREEN"

echo "G. upgrade over the same board changes nothing it already has"
UOUT="$(python3 "$INIT" upgrade "$PROJ" 2>&1)"; URC=$?
eq  "G upgrade exits 0" "$URC" "0"
has "G ...and finds the wiki seeded" "$UOUT" "already seeded"
has "G doctor is still green after it" "$(bash "$DOC" "$PROJ" 2>&1)" "$GREEN"

echo "H. the harness this unit's red surfaced in"
if [ -n "${PEARDE_HARNESSES:-}" ]; then
  skip "the readme quickstart is left to the sweep's own run of it — it runs \
that harness directly, and running it twice buys nothing"
else
  QS="$(bash "$NEIGHBOUR/quickstart.sh" </dev/null 2>&1)"; QRC=$?
  eq  "H quickstart.sh exits 0" "$QRC" "0"
  has "H ...and every check passed" "$(printf '%s\n' "$QS" | tail -1)" " 0 fail"
  # quickstart prints only its FAILs, so the leg is read off what it shows
  has "H ...including the leg this unit owes it" "$QS" \
      "\$ HOME=<a home with no Obsidian config> pearde doctor"
  has "H ...whose vault row answered there" "$QS" "Obsidian not installed here"
  has "H ...and whose doctor closed green there" "$QS" "$GREEN"
  [ "$QRC" = 0 ] || printf '%s\n' "$QS" | grep '^FAIL' | sed 's/^/      /'
fi

echo "I. nothing of this machine's was written to"
python3 "$COPY/resources/board/serve.py" stop >/dev/null 2>&1
eq  "I the live daemon's registry is untouched" \
    "$( [ -f "$REG" ] && cksum < "$REG" )" "$REG_BEFORE"

echo
echo "$((PASS+FAIL+SKIP)) checks · $PASS pass · $FAIL fail · $SKIP skip"
[ "$FAIL" = 0 ]
